name: yachay_prompts
description: Plataforma Multilingüe para Generación de Prompts Educativos con IA.
publish_to: 'none'
version: 1.0.2+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    # --- Dependencias de audio y video ---
  video_player: ^2.10.0

    # --- Dependencias de UI y Utilidad ---
  cupertino_icons: ^1.0.6
  dropdown_button2: ^2.3.9
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  collection: ^1.18.0
  share_plus: ^11.0.0
  path_provider: ^2.1.3
  path: ^1.8.3
  provider: ^6.0.5
  image_picker: ^1.0.7
  url_launcher: ^6.2.4
  uuid: ^4.4.0         # <--- AÑADIDA
  open_filex: ^4.3.2   # <--- AÑADIDA
  http: ^0.13.6
  logger: ^2.0.2
  # --- Dependencias de Firebase ---
  firebase_core: ^3.14.0
  firebase_app_check: ^0.3.2+7
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  cloud_functions: ^5.5.2
  firebase_storage: ^12.4.7
  mercadopago_sdk: ^1.3.0
  # --- Dependencias para Almacenamiento Local (SQLite) ---
  sqflite: ^2.3.3+1

  # --- Dependencias de PDF y Impresión ---
  pdf: ^3.10.8
  printing: ^5.11.1
  rxdart: ^0.27.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.11

# Esta sección es para configurar el ícono de la app
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/yachay_logo.png"

# Nueva sección para el splash screen nativo
flutter_native_splash:
  color: "#FFFFFF" # Color de fondo del splash screen (en formato HEX). Puedes usar tu color principal aquí.
  image: assets/images/yachay_logo.png # <--- RUTA A TU LOGO PRINCIPAL (PNG)
  fullscreen: true # Opcional: si quieres que el splash screen ocupe toda la pantalla

  android_gravity: center # Opcional: alineación de la imagen en Android (center, top, bottom, etc.)
  ios_content_mode: center # Opcional: alineación de la imagen en iOS (center, scaleAspectFit, etc.)


flutter:
  uses-material-design: true
  generate: true # Para la internacionalización (i18n)

  assets:
    - assets/images/