// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJRMAtLddrvKEKm2BkmiHa5SGt_xaDHY8',
    appId: '1:467788212563:web:9d47882ab1dd13ac6159a6',
    messagingSenderId: '467788212563',
    projectId: 'yachay-prompts',
    authDomain: 'yachay-prompts.firebaseapp.com',
    storageBucket: 'yachay-prompts.firebasestorage.app',
    measurementId: 'G-63QJ52DQS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBNb9pqaELjB46dF6XKRqA4W995dYOIAI',
    appId: '1:467788212563:android:278888211a00f39b6159a6',
    messagingSenderId: '467788212563',
    projectId: 'yachay-prompts',
    storageBucket: 'yachay-prompts.firebasestorage.app',
  );
}
